FROM mysql

#ARG TZ=UTC
#ENV TZ ${TZ}
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#
#RUN chown -R mysql:root /var/lib/mysql/

#ROOTPW="dphp"
#NEWSUSER="mbmgc"
#NEWSUSERPW="mbmgc"
#
#
#CREATE DATABASE ${NEWSUSER} DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
#CREATE USER '${NEWSUSER}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${NEWSUSERPW}';
#GRANT ALL ON ${NEWSUSER}.* TO '${NEWSUSER}'@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY '${NEWSUSERPW}';
